### PR TITLE
Show tick to confirm new tags were saved

### PR DESCRIPTION
**Pull request by kabirgh**
Displays a small green tick to the right of the tags list when a change to them is made

Misc:
* Fixed bug where icons for expanding card and showing options weren't appearing
* Added dummy data to dev server runs

### CODE REVIEW

**Comment by varung97** [comment]
Could we shift the tick a little to the right? It's flush with the input box, so looks a bit weird.
Can also consider not showing the tick if the tags aren't changed (not sure how much effort this will be)
Also, maybe need to add a tick for editing title also

**Comment by kabirgh** [comment]
Yep I've been trying to nudge it away from the input box, but haven't been able to do it yet. Will update the pull request to do the same for the title.

**Comment by kabirgh** [comment]
Tried to add a tick after for title edits, but shouldShowTitleTick doesn't seem to change value. It always shows false when logging in SpoilerCard, but true when set in SpoilerCardContainer. Not sure why

**Comment by varung97** [comment]
Interestingly, if the title isn't edited at all, then the tick shows up...

**Comment by varung97** [comment]
Oh and I think we should do some error checking for invalid tags also, what do you think?

**Comment by varung97** [comment]
Hmmm for some reason the constructor for `SpoilerCardContainer` is called after the title changes... I guess that resets `shouldShowTitleTick` to `false`. No idea why this is happening though...

**Comment by kabirgh** [comment]
That's odd... Can't find any related issues on SO. Not sure why it happens with the title only, and not the tags too. Will remove it for now and raise an issue.

**Comment by varung97** [comment]
Alright

**Pull request merged**
