### PR TITLE
Implement see more functionality

### PR DESCRIPTION
**Pull request by varung97**

### CODE REVIEW

**Review by kabirgh — APPROVED** [review]
Reviewed. Any solution for present and future merge conflicts with files in `dist/`?

**Comment by varung97** [comment]
A sort of hacky solution would be to gitignore `dist/` for now, and when we want to create a release, bring it back in, then ignore again after that. We could potentially automate that process though, with a shell script I guess.
The massive line changes are also irritating me, in fact :(

**Comment by kabirgh** [comment]
Sounds good. We should edit the README to guide users to the latest release's source code then. Right now it asks to only to clone the repo

**Comment by varung97** [comment]
I'll add that as an issue, and work on it when I get time. Will also merge this in today.

**Pull request merged**
